### ISSUE TITLE
UI - Dynamic Speech Bubbles

### ISSUE THREAD

**Issue by tsnl** [ilinxcode/whale-beta#6]
We currently load an image of a speech bubble that does not resize to fit the borders of a tile rectangle.

Either:
- Create a new tile that stretches images out to fit tile-rect borders (which I'm not a fan of, could lead to very bad distortion and is very inflexible), or
- Create a new tile that uses the HTML5 Canvas' drawing methods to dynamically draw a speech bubble and an arrow to fit certain text. This tile should be parametrized with its own rectangle to fit text in as well as another tile coordinate for the notch at the bottom. This tile should also support a method named `smoothResize` that, over a certain duration of time, resizes the speech bubble to fit another rectangle by mutating its tileRect in the render loop and then calls a completion handler.

This (along with #5 ) would allow us to let the mascot say whatever we want to the player without fear of the bubble not scaling to fit it.

**Comment by richiesomething** [comment]
submitted pull request
