### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by kristopolous** [ilinxcode/whale-beta#9]

**Comment by kristopolous** [comment]
Aviv needs to deliver UX

**Comment by tsnl** [comment]
The following need to be implemented on the front-end:
- A polished sign-up page which accepts a user-name, password, and email ID. 
- A sign-in page which accepts an email ID and a password.
- Modifications to pages across Whale to reflect the 'current_user'.

Demos for the sign up and log in page already exist at `templates/create-account.html` and `templates/login-account.html`. Both just use forms and Jinja templates to communicate with the server.

Focus only on front-end work for now. If you need backend features, contact @Thundersnail.

**Comment by RattMoth** [comment]
I'm going to start this by cleaning up the form styling (nothing drastic, just giving it a better visual structure and probably using external CSS style sheets). I'll do my best to focus on the structure, leaving the styling for later once we have a UX designed. Let me know if this sounds alright!

**Comment by RattMoth** [comment]
Submitted PR
